services:
  db:
    image: postgres:16
    container_name: db_atividade
    env_file:
      - .env  # O Docker vai procurar as variáveis aqui dentro
    environment:
      # O Docker mapeia as variáveis do seu .env para as do Postgres
      POSTGRES_DB: ${DB_NAME:-biblioteca}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: