DROP TABLE livro CASCADE;
DROP TABLE categoria CASCADE;
DROP TABLE editora CASCADE;
DROP TABLE autor CASCADE;
DROP TABLE usuario CASCADE;
DROP TABLE emprestimos CASCADE;
DROP TABLE reserva CASCADE;
DROP TABLE multa CASCADE;